In [5]:
import numpy as np

a = np.random.randn(5)

print(a)

print (a.shape)

print(a.T)

#assert(a.shape == (5,1))

print(np.dot(a,a.T))

[ 0.84272255  1.49558622  0.71270849  0.22639767 -0.91677526]
(5,)
[ 0.84272255  1.49558622  0.71270849  0.22639767 -0.91677526]


AssertionError: 

In [6]:
a = np.random.randn(5,1)

print (a)

print (a.T)

#assert(a.shape == (5,1))

print(np.dot(a,a.T))

[[-0.97227657]
 [ 0.37326227]
 [-0.57284441]
 [-0.58543066]
 [-1.1910989 ]]
[[-0.97227657  0.37326227 -0.57284441 -0.58543066 -1.1910989 ]]
[[ 0.94532172 -0.36291416  0.5569632   0.56920051  1.15807755]
 [-0.36291416  0.13932472 -0.2138212  -0.21851918 -0.44459228]
 [ 0.5569632  -0.2138212   0.32815072  0.33536068  0.68231435]
 [ 0.56920051 -0.21851918  0.33536068  0.34272906  0.69730582]
 [ 1.15807755 -0.44459228  0.68231435  0.69730582  1.41871659]]
