Make sure you have ipykernal installed in your jupyter notebook. If not, you can install it by running the following command in your terminal:
```bash
conda install -n localdev ipykernel
```

You also need to have numpy installed, which you can install by using the command:
```bash
conda install -n localdev numpy
```

In [2]:
import numpy as np

a = np.array([1, 2, 3])
print(a);

[1 2 3]


In [10]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
    
print(c)
print("For loop: " + str(1000*(toc-tic)) + "ms")

249835.26365785982
Vectorized version: 1.524209976196289ms
249835.26365785382
For loop: 441.9081211090088ms


Neural Network programming guideline.
Whenever possible, avoid explicit for-loops.


Vectorizing a Logistal Regression
z(1) = wTx(1) + b
There is a way to compute all z's in one line of code:

Z = np.dot(w.T, X) + b
Where X is the input matrix of shape (nx, m) and Z is the output vector of shape (1, m).
Where b is a 1:1 matrix
Refer to screenshot in my Neural Network notes for more details.
The b is considered as a broadcasted matrix.

We also have a(1) = sigmoid(z(1))
We can turn all the a's into capital A as a matrix of shape (1, m) by using the following code with numpy:
A = sigmoid(Z)

Broadcasting in Python Example

In [13]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0], 
              [1.2, 104.0, 52.0, 8.0], 
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [14]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [15]:
percentage = 100*A/cal.reshape(1, 4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
